swagger: "2.0"
info:
  description: idk
  version: "19.11.0"
  title: TravelStorms Main API Gateway
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/ts-weather"

# Paths supported by the server application
paths:
  /routeForcast/{lat}/{lon}/{trans_id}:
    get:
      operationId: route_forcast.getData
      tags:
        - "Weather"
      summary: Grab weather forecast for route
      description: Grab weather forecast for route
      parameters:
        - name: lat
          in: path
          description: lattitude
          type: string
          required: True
        - name: lon
          in: path
          description: longitude
          type: string
          required: True
        - name: trans_id
          in: path
          description: trans_id
          type: string
          required: True
      responses:
        200:
          description: Weather Results successfully grabbed
